---
title: A rainbowR Presentation
subtitle: Subtitle
author: Your Name
date: last-modified
date-format: long
footer: <https://conference.rainbowr.org>
format: 
  rainbowrpres-revealjs:
    progress: false
    slide-number: false
    menu: false
---

# Welcome to rainbowR conference 2026! {.inverse .larger200 .center-h}

::: {.notes}
- inaugural 
- about the conference
- about the community
:::

## A safe and welcoming space for LGBTQ+ folks and allies

[rainbowr.org/coc](https://rainbowr.org/coc){.larger200}

. . . 

::: {.callout-tip}
Let us know if you experience or witness anything that feels uncomfortable.

- [coc@rainbowr.org](mailto:coc@rainbowr.org)
- [reporting form](https://docs.google.com/forms/d/e/1FAIpQLSfOMgx43xj6DuWccAoA5D4Mc1y53EqfpWyOYZkle1z3A-XupQ/viewform)
- message in Discord (see code-of-conduct channel)
:::


::: {.notes}
CoC sets out the community standards and expectations.
However small.
Moderators on Zoom and in Discord, but we might not see everything.
CoC is not punitative
:::

## [Why a rainbowR conference?]{.pink} {.inverse .larger150}

[center LGBTQ+ members of the R community]{.red}

[learn about R]{.orange}

[understand LGBTQ+ data]{.yellow}

[make connections]{.green}

[have fun!]{.blue}

## Schedule

[conference.rainbowr.org/schedule](conference.rainbowr.org/schedule)

| Time (UTC)  | Event                                        |
|-------------|----------------------------------------------|
| 16:15-17:00 | Keynote: Studying queer data while living it |
| 17:00-18:00 | Talks 1                                      |
| 18:00-18:30 | Birds of a feather                           |
| 18:30-19:15 | Lightning talks                              |
| 19:15-20:15 | Talks 2                                      |
| 20:15-20:30 | *break*                                      |
| 20:30-21:30 | Keynote: Claude Code for R *(and close)*                  |

## Recordings

- Regular and lightning talks pre-recorded and will be shared afterwards
- *Claude Code for R* will be recorded live 
- *Studying queer data while living it* will **not** be recorded
- Socials not recorded

::: {.notes}
Zoom may ask you to agree to be recorded to join a meeting, but rest assured we will not be recording participants
:::

## Zoom chat and Q&A

- Use Q&A feature in Zoom for questions during sessions
- Use Zoom chat for general chat

## Discord

- rainbowR conference 2026 server
- invitation link (*put in chat*)
- for *asynchronous* chat (not during talk sessions)
- make and continue conversations
- will exist beyond conference

# [rainbowR]{.yellow} {.inverse .larger150}

a [community]{.green} that
[connects]{.red}, [supports]{.orange} and [promotes]{.yellow} [LGBTQ+]{.pink} people in the [R community]{.blue} and spreads awareness of [LGBTQ+]{.pink} issues through [data-driven activism]{.green}

## What we do

## How to join

# Closing {.inverse}

## Thank yous

- speakers, workshop leaders, BoF facilitators
- sponsors
- supporters
- committee

## What we do

## How to join

## After

Link to page on conf website